name: Publish

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      env:
        ${{NPM_AUTH_TOKEN}}
    - uses: "actions/npm@master"
    - name: Run a multi-line script
      run: |
        npm login
        npm publish --access=public
